"""initial scenario schema

Revision ID: caa432fb7ae8
Revises:
Create Date: 2026-10-01 21:33:53.767189
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "caa432fb7ae8"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "scenarios",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("slug", sa.String(length=120), nullable=False),
        sa.Column("title", sa.String(length=160), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("category", sa.String(length=24), nullable=False),
        sa.Column("industry_segment", sa.String(length=40), nullable=True),
        sa.Column(
            "companies",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "roles",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("difficulty", sa.SmallInteger(), nullable=False),
        sa.Column("english_level", sa.String(length=20), nullable=True),
        sa.Column("situation", sa.Text(), nullable=False),
        sa.Column(
            "ai_character",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("user_objective", sa.Text(), nullable=False),
        sa.Column(
            "target_skills",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "target_expressions",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("roleplay_instructions", sa.Text(), nullable=False),
        sa.Column(
            "evaluation_rubric",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("estimated_minutes", sa.SmallInteger(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "category IN ('interview', 'workplace', 'travel', 'daily_life')",
            name="ck_scenarios_category",
        ),
        sa.CheckConstraint(
            "status IN ('draft', 'published', 'archived')", name="ck_scenarios_status"
        ),
        sa.CheckConstraint("difficulty BETWEEN 1 AND 5", name="ck_scenarios_difficulty"),
        sa.CheckConstraint("estimated_minutes > 0", name="ck_scenarios_estimated_minutes"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    op.create_index(
        "ix_scenarios_status_category_difficulty",
        "scenarios",
        ["status", "category", "difficulty"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_scenarios_status_category_difficulty", table_name="scenarios")
    op.drop_table("scenarios")
    # ### end Alembic commands ###
